### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by skAutomation12** [grasshopper7/testngcuke4sharedwebdriver#1]
image
![image](https://user-images.githubusercontent.com/43443475/60741720-26389600-9f30-11e9-902d-9e259bfa90b6.png)

[pkg] Locators declaration of page elements;
[pkg] Actions pg object creation and init pagefactory and methods declaration to perform actions on page elements.
[pkg] runner has all runner classes TestNG
runner Class has @BeforeClass where I login to application before executing test steps to be performed on application to test the interface
[pkg] Steps
==Cucumber hooks to handle test failure and screenshot @after
==Cucumber steps ==>Access to driver is important as the navigation to url and dynamic page element handling is done from within steps
[pkg] utils==> wait, read .property, ngwebdriver for angular waits.

This all works fine when i have single thread; I tried to incorporate your design to make it parallel which i havent found any success.

How to access driver object from steps??
I donot want to navigate the url from page class;

**Comment by grasshopper7** [comment]
No need for constructor or beforeclass method in runner. Change the SharedDriver code as below.

public SharedDriver() {
         WebDriverManager.chromedriver().setup();
		WebDriver driver = DriverFactory.getDriver();
		if (driver == null) {
			driver = new ChromeDriver();
			DriverFactory.addDriver(driver);
		}
//Do your login and initial stuff here
		driver.get("http://yoursite.com/");
}
U can access driver anywhere as DriverFactory.getDriver().

**Comment by skAutomation12** [comment]
I tried using this "DriverFactory.getDriver()." outside this class and I got null pointer.
