### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by skAutomation12** [grasshopper7/testngcuke4sharedwebdriver#2]
cucumber Hooks and TestNG Annotations; 

I was able to figout based on your earlier feedback; yes it working. 

Now I would like to use Cucumber Hooks and TestNG BeforeClass and AfterClass Annotations to add reporting. 

I am sorry to bother you repeatedly but your stuff is real good.

**Comment by skAutomation12** [comment]
How to control the thread count using this Framework

**Comment by grasshopper7** [comment]
Thread count - U need to set property `dataproviderthreadcount `. Check [here ](http://grasshopper.tech/466/)and search for dataproviderthreadcount 

The [pom ](https://github.com/grasshopper7/cuke4testngparallel/blob/83b8c03fe65751d77a4e32e386c35e61f47482db/testngparallel/pom.xml#L68)has a similar setting of what u r looking for. 

For reporting just use [cluecumber](https://github.com/trivago/cluecumber-report-plugin).
