### ISSUE TITLE
implementation queries

### ISSUE THREAD

**Issue by Jayashree-swapstech** [grasshopper7/testngcuke4sharedwebdriver#3]
When and how addShutdownHook is getting called? 
How and where removeDriver is called in snippet? 
Driver.quit is not happening at all.

**Comment by grasshopper7** [comment]
> When and how addShutdownHook is getting called?

This is called when the DriverFactory class is initialized.

> How and where removeDriver is called in snippet?

This is not required in the current example. This is helpful if u want to close down a specific driver instance manually.

> Driver.quit is not happening at all.

Cannot help unless u provide more specific details.

**Comment by Jayashree-swapstech** [comment]
I think its problem with latest chromedriver 77.  (Selenium and webdrivermanager version remains same as yours) 
Can you check if it works for you perfectly as before for latest version too?
i.e. if threadcount is kept 2. for 3rd and later scenarios picked - session connection is refused.

**Comment by grasshopper7** [comment]
It is happening intermittently. I ran it seven times and it failed once on Chrome. No idea why so?
Works perfectly on firefox. Even then I have removed the stream method call and add maximize browser.

**Comment by Jayashree-swapstech** [comment]
Yes, Weird behavior intermittently.
I’ve added sleep just prior to adddriver statement so that 3rd  scenario onwards it gets some breathing time in launching…. I didn’t understand logic  behind this, but it happened to give me good result no connection error now.
In case, you understand the rational do let me know as well. 😊

Thanks,
Jayashree

Sent from Mail for Windows 10
